---
- name: Deploy NodeJS App using Pull Model
  hosts: localhost
  become: yes
  tasks:
    - name: Install Node.js and npm
      apt:
        name:
          - nodejs
          - npm
        state: present
        update_cache: yes

    - name: Install PM2 globally
      npm:
        name: pm2
        global: yes

    # ... rest of your existing tasks ...
